name: "Create PR"
on: push

jobs:
  create-pr-on-push:
    #if: ${{ (contains(github.event.head_commit.message, 'BUG') || contains(github.event.head_commit.message, 'IMP'))  && github.event.pull_request.merged == false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        head: ${{ github.ref }}
        base: main
        title: ${{ github.event.head_commit.message }}
