name: Notion DB to Github PR

on:
  # Notion 테이블에서 수정 이벤트 발생 시
  push:
    branches:
      - main
           

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Notion API 토큰 설정
      - name: Set Notion API Token
        env:        
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN_2 }}
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo "::set-env name=NOTION_API_TOKEN::${{ secrets.NOTION_API_TOKEN_2 }}"

      # Github PAT 설정
      - name: Set Github PAT
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: echo "::set-env name=GITHUB_PAT::${{ secrets.GH_PAT }}"

      # Notion 데이터베이스 정보 가져오기
      - name: Get Notion Database Info
        id: notion_db_info
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${{ env.NOTION_API_TOKEN }}" \
            -H "Notion-Version: 2022-06-28" \
            "https://api.notion.so/v1/databases/961a46b0a66d403e9a59e617db721732"

      # Notion 테이블에서 변경된 페이지 목록 추출
      - name: Get Changed Pages
        id: changed_pages
        run: |
          jq -r '.results[] | select(.has_changes)' ${{ steps.notion_db_info.outputs.result }}

      # 각 변경된 페이지에 대한 Github Pull Request 생성
      - name: Create Pull Request for Each Changed Page
        uses: peter-evans/create-pull-request@v3
        with:
          # Github 저장소 정보
          repo: ${{ secrets.GH_REPOSITORY }}
          branch: ${{ github.ref }}
          # Pull Request 제목 및 본문 구성
          title: "Notion DB 변경: {{ .page.title }}"
          body: |
            - 변경된 페이지: {{ .page.url }}
            - 변경 내용: {{ .changes }}
          # Github PAT를 사용하여 Pull Request 생성
          token: ${{ env.GITHUB_PAT }}

