name: ci

on:
  pull_request:
    types: [opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: kolesnikov-pasha/github-pr-linker@v1.0.1
      with:
        database-id: 961a46b0a66d403e9a59e617db721732
        notion-token: ${{ secrets.NOTION_TOKEN }}
