name: Notion Database to Github Pull Request

on:
  # Notion 데이터베이스 수정 이벤트를 감지
  push:
    branches:
      - frontend
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Notion API 라이브러리 설치
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install notion-api

      # 2. Notion 데이터베이스 정보 가져오기
      - name: Get Notion Database Info
        id: get_notion_info
        run: |
          node ./get-notion-info.js \
            --token ${{ secrets.NOTION_TOKEN }} \
            --database-id ${{ secrets.NOTION_DATABASE }} \
            --since ${{ github.event.before }} \
            --until ${{ github.event.after }}

      # 3. Notion 데이터베이스 변경 사항을 Github Pull Request로 변환
      - name: Create Github Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "Notion Database Updates - ${{ github.event.head_commit.message }}"
          body: |
            ${{ steps.get_notion_info.outputs.pull_request_body }}

          branch: ${{ github.event.head_commit.sha }}
          base: main
