name: "Create PR"
on: push

jobs:
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Create pull request
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        head: ${{ github.ref }}
        base: main
        title: ${{ github.event.head_commit.message }}
