name: Notion 테이블 변경값 호출

on:
  - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Webhook payload 처리
        # Webhook payload에서 변경값 추출
        run: echo "Notion 테이블 변경값: ${{ github.event.body.data }}"
